/**
 * Cloudflared Docker Service
 * Manages cloudflared container operations and configuration
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs/promises';
import * as path from 'path';
import { TunnelCredentials } from './KimbapCloudApiService';

const execAsync = promisify(exec);

export interface CloudflaredConfig {
  tunnel: string;
  credentialsFile?: string;
  ingress: Array<{
    hostname?: string;
    service: string;
    originRequest?: {
      noTLSVerify?: boolean;
      connectTimeout?: string;
      tcpKeepAlive?: string;
    };
  }>;
}

export class CloudflaredDockerService {
  private readonly configDir: string;
  private readonly configFile: string;
  private readonly credentialsDir: string;
  private readonly containerName: string = 'kimbap-cloudflared';

  constructor(baseDir: string = '.') {
    this.configDir = path.join(baseDir, 'cloudflared');
    this.configFile = path.join(this.configDir, 'config.yml');
    this.credentialsDir = this.configDir;
  }

  /**
   * Ensure cloudflared config directory exists
   */
  private async ensureConfigDir(): Promise<void> {
    try {
      await fs.mkdir(this.configDir, { recursive: true });
    } catch (error) {
      console.error('Failed to create cloudflared config directory:', error);
      throw error;
    }
  }

  /**
   * Write cloudflared configuration file
   * @param configYaml YAML configuration content as string
   */
  async writeConfig(configYaml: string): Promise<void> {
    await this.ensureConfigDir();
    
    try {
      await fs.writeFile(this.configFile, configYaml, 'utf8');
      console.log('Cloudflared config written to:', this.configFile);
    } catch (error) {
      console.error('Failed to write cloudflared config:', error);
      throw error;
    }
  }

  /**
   * Write tunnel credentials file
   * @param tunnelId Tunnel ID
   * @param credentials Tunnel credentials
   */
  async writeCredentials(tunnelId: string, credentials: TunnelCredentials): Promise<string> {
    await this.ensureConfigDir();
    
    const credentialsFile = path.join(this.credentialsDir, `${tunnelId}.json`);
    
    try {
      await fs.writeFile(credentialsFile, JSON.stringify(credentials, null, 2), 'utf8');
      console.log('Credentials written to:', credentialsFile);
      return credentialsFile;
    } catch (error) {
      console.error('Failed to write credentials:', error);
      throw error;
    }
  }

  /**
   * Generate YAML configuration content
   * @param config Configuration object
   * @returns YAML string
   */
  private generateConfigYaml(config: CloudflaredConfig): string {
    let yaml = `# Cloudflare Tunnel Configuration
# Generated by CloudflaredDockerService

tunnel: ${config.tunnel}
`;

    if (config.credentialsFile) {
      yaml += `credentials-file: ${config.credentialsFile}\n`;
    }

    yaml += '\ningress:\n';

    for (const rule of config.ingress) {
      if (rule.hostname) {
        yaml += `  - hostname: ${rule.hostname}\n`;
        yaml += `    service: ${rule.service}\n`;
        
        if (rule.originRequest) {
          yaml += '    originRequest:\n';
          if (rule.originRequest.noTLSVerify !== undefined) {
            yaml += `      noTLSVerify: ${rule.originRequest.noTLSVerify}\n`;
          }
          if (rule.originRequest.connectTimeout) {
            yaml += `      connectTimeout: ${rule.originRequest.connectTimeout}\n`;
          }
          if (rule.originRequest.tcpKeepAlive) {
            yaml += `      tcpKeepAlive: ${rule.originRequest.tcpKeepAlive}\n`;
          }
        }
      } else {
        // Catch-all rule
        yaml += `  - service: ${rule.service}\n`;
      }
    }

    return yaml;
  }

  /**
   * Load configuration from file
   * @returns Configuration content
   */
  async loadConfig(): Promise<string> {
    try {
      const content = await fs.readFile(this.configFile, 'utf8');
      return content;
    } catch (error) {
      console.error('Failed to load cloudflared config:', error);
      throw error;
    }
  }

  /**
   * Check if Docker is running
   */
  private async isDockerRunning(): Promise<boolean> {
    try {
      await execAsync('docker info');
      return true;
    } catch (error) {
      console.warn('Docker is not running');
      return false;
    }
  }

  /**
   * Check if cloudflared container exists
   */
  async containerExists(): Promise<boolean> {
    try {
      const { stdout } = await execAsync(`docker ps -a --filter "name=${this.containerName}" --format "{{.Names}}"`);
      return stdout.trim() === this.containerName;
    } catch (error) {
      console.error('Failed to check container existence:', error);
      return false;
    }
  }

  /**
   * Check if cloudflared container is running
   */
  async isRunning(): Promise<boolean> {
    try {
      const { stdout } = await execAsync(`docker ps --filter "name=${this.containerName}" --filter "status=running" --format "{{.Names}}"`);
      return stdout.trim() === this.containerName;
    } catch (error) {
      console.error('Failed to check container status:', error);
      return false;
    }
  }

  /**
   * Start cloudflared container
   * @param waitForReady Whether to wait for container to be ready
   */
  async start(waitForReady: boolean = true): Promise<void> {
    if (!await this.isDockerRunning()) {
      throw new Error('Docker is not running');
    }

    // Check if already running
    if (await this.isRunning()) {
      console.log('Cloudflared container is already running');
      return;
    }

    try {
      // Check if container exists but is stopped
      if (await this.containerExists()) {
        console.log('Starting existing cloudflared container...');
        await execAsync(`docker start ${this.containerName}`);
      } else {
        console.log('Starting new cloudflared container...');
        await execAsync('docker compose up -d cloudflared');
      }

      if (waitForReady) {
        await this.waitForContainer();
      }

      console.log('Cloudflared container started successfully');
    } catch (error) {
      console.error('Failed to start cloudflared container:', error);
      throw error;
    }
  }

  /**
   * Stop cloudflared container
   */
  async stop(): Promise<void> {
    if (!await this.isDockerRunning()) {
      console.warn('Docker is not running');
      return;
    }

    if (!await this.isRunning()) {
      console.log('Cloudflared container is not running');
      return;
    }

    try {
      console.log('Stopping cloudflared container...');
      await execAsync(`docker stop ${this.containerName}`);
      console.log('Cloudflared container stopped');
    } catch (error) {
      console.error('Failed to stop cloudflared container:', error);
      throw error;
    }
  }

  /**
   * Restart cloudflared container to apply new configuration
   */
  async restart(): Promise<void> {
    if (!await this.isDockerRunning()) {
      throw new Error('Docker is not running');
    }

    try {
      console.log('Restarting cloudflared container...');
      
      if (await this.containerExists()) {
        await execAsync(`docker restart ${this.containerName}`);
      } else {
        // If container doesn't exist, start it
        await this.start();
        return;
      }

      await this.waitForContainer();
      console.log('Cloudflared container restarted successfully');
    } catch (error) {
      console.error('Failed to restart cloudflared container:', error);
      throw error;
    }
  }

  /**
   * Wait for container to be ready
   * @param maxRetries Maximum number of retries
   * @param delayMs Delay between retries in milliseconds
   */
  private async waitForContainer(maxRetries: number = 10, delayMs: number = 1000): Promise<void> {
    for (let i = 0; i < maxRetries; i++) {
      if (await this.isRunning()) {
        // Additional check for container health if needed
        await new Promise(resolve => setTimeout(resolve, 1000)); // Give it a second to fully start
        return;
      }
      await new Promise(resolve => setTimeout(resolve, delayMs));
    }
    throw new Error('Cloudflared container failed to start within timeout');
  }

  /**
   * Get container logs
   * @param lines Number of lines to retrieve
   */
  async getLogs(lines: number = 50): Promise<string> {
    if (!await this.containerExists()) {
      return 'Container does not exist';
    }

    try {
      const { stdout } = await execAsync(`docker logs --tail ${lines} ${this.containerName}`);
      return stdout;
    } catch (error) {
      console.error('Failed to get container logs:', error);
      throw error;
    }
  }

  /**
   * Remove cloudflared container completely
   */
  async remove(): Promise<void> {
    if (!await this.isDockerRunning()) {
      console.warn('Docker is not running');
      return;
    }

    if (!await this.containerExists()) {
      console.log('Cloudflared container does not exist');
      return;
    }

    try {
      // Stop if running
      if (await this.isRunning()) {
        await this.stop();
      }

      console.log('Removing cloudflared container...');
      await execAsync(`docker rm ${this.containerName}`);
      console.log('Cloudflared container removed');
    } catch (error) {
      console.error('Failed to remove cloudflared container:', error);
      throw error;
    }
  }

  /**
   * Setup cloudflared with tunnel configuration
   * @param tunnelId Tunnel ID
   * @param credentials Tunnel credentials
   * @param hostname Hostname for the tunnel
   * @param localPort Local port to forward
   */
  async setupTunnel(
    tunnelId: string, 
    credentials: TunnelCredentials, 
    hostname: string, 
    localPort: number
  ): Promise<void> {
    // Write credentials
    await this.writeCredentials(tunnelId, credentials);

    // Generate and write config
    const config: CloudflaredConfig = {
      tunnel: tunnelId,
      credentialsFile: `/etc/cloudflared/${tunnelId}.json`,
      ingress: [
        {
          hostname: hostname,
          service: `http://host.docker.internal:${localPort}`,
          originRequest: {
            noTLSVerify: true,
            connectTimeout: '30s',
            tcpKeepAlive: '30s'
          }
        },
        {
          // Catch-all rule
          service: 'http_status:404'
        }
      ]
    };

    // Generate YAML and write config
    const configYaml = this.generateConfigYaml(config);
    await this.writeConfig(configYaml);

    // Restart container to apply configuration
    await this.restart();
  }

  /**
   * Check if cloudflared image is available
   */
  async imageExists(): Promise<boolean> {
    try {
      const { stdout } = await execAsync('docker images cloudflare/cloudflared --format "{{.Repository}}"');
      return stdout.includes('cloudflare/cloudflared');
    } catch (error) {
      console.error('Failed to check cloudflared image:', error);
      return false;
    }
  }

  /**
   * Pull cloudflared Docker image
   */
  async pullImage(): Promise<void> {
    try {
      console.log('Pulling cloudflare/cloudflared image...');
      await execAsync('docker pull cloudflare/cloudflared:latest');
      console.log('Cloudflared image pulled successfully');
    } catch (error) {
      console.error('Failed to pull cloudflared image:', error);
      throw error;
    }
  }

  /**
   * Initialize cloudflared (pull image if needed and create config directory)
   */
  async initialize(): Promise<void> {
    // Ensure Docker is running
    if (!await this.isDockerRunning()) {
      throw new Error('Docker is not running. Please start Docker first.');
    }

    // Ensure config directory exists
    await this.ensureConfigDir();

    // Check and pull image if needed
    if (!await this.imageExists()) {
      await this.pullImage();
    }

    console.log('Cloudflared Docker service initialized');
  }
}

// Export singleton instance for convenience
export const cloudflaredService = new CloudflaredDockerService();