package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"unicode"

	"github.com/dunialabs/kimbap-core/internal/actions"
	"github.com/spf13/cobra"
)

func newGenerateCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate typed client snippets for installed actions",
		RunE: func(cmd *cobra.Command, _ []string) error {
			return cmd.Help()
		},
	}

	cmd.AddCommand(newGenerateTSCommand())
	cmd.AddCommand(newGeneratePyCommand())

	return cmd
}

func newGenerateTSCommand() *cobra.Command {
	var outputPath string
	var service string

	cmd := &cobra.Command{
		Use:   "ts",
		Short: "Generate TypeScript input interfaces for installed actions",
		RunE: func(_ *cobra.Command, _ []string) error {
			cfg, err := loadAppConfig()
			if err != nil {
				return err
			}
			defs, err := loadInstalledActions(cfg)
			if err != nil {
				return err
			}

			grouped := groupActionsByNamespace(defs, service)
			content := renderTypeScriptSnippets(grouped)
			return writeGeneratedOutput(content, outputPath, "ts", countGroupedActions(grouped))
		},
	}

	cmd.Flags().StringVarP(&outputPath, "output", "o", "", "output file path (defaults to stdout)")
	cmd.Flags().StringVar(&service, "service", "", "generate snippets only for one service")

	return cmd
}

func newGeneratePyCommand() *cobra.Command {
	var outputPath string
	var service string

	cmd := &cobra.Command{
		Use:   "py",
		Short: "Generate Python TypedDict inputs for installed actions",
		RunE: func(_ *cobra.Command, _ []string) error {
			cfg, err := loadAppConfig()
			if err != nil {
				return err
			}
			defs, err := loadInstalledActions(cfg)
			if err != nil {
				return err
			}

			grouped := groupActionsByNamespace(defs, service)
			content := renderPythonSnippets(grouped)
			return writeGeneratedOutput(content, outputPath, "py", countGroupedActions(grouped))
		},
	}

	cmd.Flags().StringVarP(&outputPath, "output", "o", "", "output file path (defaults to stdout)")
	cmd.Flags().StringVar(&service, "service", "", "generate snippets only for one service")

	return cmd
}

func groupActionsByNamespace(defs []actions.ActionDefinition, serviceFilter string) map[string][]actions.ActionDefinition {
	grouped := map[string][]actions.ActionDefinition{}
	for _, def := range defs {
		if strings.TrimSpace(serviceFilter) != "" && !strings.EqualFold(def.Namespace, serviceFilter) {
			continue
		}
		grouped[def.Namespace] = append(grouped[def.Namespace], def)
	}

	for namespace := range grouped {
		sort.Slice(grouped[namespace], func(i, j int) bool {
			return grouped[namespace][i].Name < grouped[namespace][j].Name
		})
	}

	return grouped
}

func renderTypeScriptSnippets(grouped map[string][]actions.ActionDefinition) string {
	var b strings.Builder
	namespaces := sortedNamespaces(grouped)

	_, _ = fmt.Fprintf(&b, "// Auto-generated by kimbap generate ts\n\n")

	for _, namespace := range namespaces {
		_, _ = fmt.Fprintf(&b, "// Service: %s\n\n", namespace)
		for _, def := range grouped[namespace] {
			desc := strings.TrimSpace(def.Description)
			if desc == "" {
				desc = "No description"
			}
			_, _ = fmt.Fprintf(&b, "/** %s — %s */\n", def.Name, desc)
			_, _ = fmt.Fprintf(&b, "export interface %s {\n", actionInputTypeName(def.Name))

			if def.InputSchema != nil && len(def.InputSchema.Properties) > 0 {
				requiredSet := requiredFields(def.InputSchema)
				keys := sortedPropertyKeys(def.InputSchema)
				for _, key := range keys {
					prop := def.InputSchema.Properties[key]
					required := requiredSet[key]
					requiredLabel := "optional"
					optionalMark := "?"
					if required {
						requiredLabel = "required"
						optionalMark = ""
					}
					_, _ = fmt.Fprintf(&b, "  /** %s */\n", requiredLabel)
					_, _ = fmt.Fprintf(&b, "  %s%s: %s;\n", tsFieldName(key), optionalMark, tsSchemaType(prop))
				}
			}

			_, _ = fmt.Fprintf(&b, "}\n\n")
			_, _ = fmt.Fprintf(&b, "// Usage: %s\n\n", usageLine(def))
		}
	}

	return b.String()
}

func renderPythonSnippets(grouped map[string][]actions.ActionDefinition) string {
	var b strings.Builder
	namespaces := sortedNamespaces(grouped)

	_, _ = fmt.Fprintf(&b, "# Auto-generated by kimbap generate py\n")
	_, _ = fmt.Fprintf(&b, "from typing import Any, TypedDict\n")
	_, _ = fmt.Fprintf(&b, "try:\n")
	_, _ = fmt.Fprintf(&b, "    from typing import Required\n")
	_, _ = fmt.Fprintf(&b, "except ImportError:\n")
	_, _ = fmt.Fprintf(&b, "    from typing_extensions import Required\n\n")

	for _, namespace := range namespaces {
		_, _ = fmt.Fprintf(&b, "# Service: %s\n\n", namespace)
		for _, def := range grouped[namespace] {
			desc := strings.TrimSpace(def.Description)
			if desc == "" {
				desc = "No description"
			}

			_, _ = fmt.Fprintf(&b, "# %s — %s\n", def.Name, desc)
			_, _ = fmt.Fprintf(&b, "# Usage: %s\n", usageLine(def))

			if def.InputSchema == nil || len(def.InputSchema.Properties) == 0 {
				_, _ = fmt.Fprintf(&b, "class %s(TypedDict, total=False):\n", actionInputTypeName(def.Name))
				_, _ = fmt.Fprintf(&b, "    pass\n\n")
				continue
			}

			keys := sortedPropertyKeys(def.InputSchema)
			needsFunctional := pyNeedsFunctionalSyntax(keys)

			if needsFunctional {
				renderPythonFunctionalTypedDict(&b, def, keys)
			} else {
				renderPythonClassTypedDict(&b, def, keys)
			}
		}
	}

	return b.String()
}

// pyNeedsFunctionalSyntax returns true if any property key is a Python keyword
// or not a valid Python identifier, requiring functional TypedDict syntax to
// preserve the exact dict key (class syntax would mangle it).
func pyNeedsFunctionalSyntax(keys []string) bool {
	for _, key := range keys {
		if pythonKeywords[key] || !isIdentifier(key) {
			return true
		}
	}
	return false
}

// renderPythonFunctionalTypedDict emits functional TypedDict syntax:
//
//	XInput = TypedDict('XInput', {'from': str, 'to': str}, total=False)
//
// This preserves the exact API key names even when they are Python keywords.
func renderPythonFunctionalTypedDict(b *strings.Builder, def actions.ActionDefinition, keys []string) {
	typeName := actionInputTypeName(def.Name)
	requiredSet := requiredFields(def.InputSchema)
	_, _ = fmt.Fprintf(b, "%s = TypedDict(%s, {\n", typeName, pySingleQuotedLiteral(typeName))
	for _, key := range keys {
		prop := def.InputSchema.Properties[key]
		typStr := pySchemaType(prop)
		if requiredSet[key] {
			typStr = "Required[" + typStr + "]"
		}
		_, _ = fmt.Fprintf(b, "    %s: %s,\n", pySingleQuotedLiteral(key), typStr)
	}
	_, _ = fmt.Fprintf(b, "}, total=False)\n\n")
}

func pySingleQuotedLiteral(value string) string {
	escaped := strings.ReplaceAll(value, "\\", "\\\\")
	escaped = strings.ReplaceAll(escaped, "'", "\\'")
	return "'" + escaped + "'"
}

func renderPythonClassTypedDict(b *strings.Builder, def actions.ActionDefinition, keys []string) {
	typeName := actionInputTypeName(def.Name)
	requiredSet := requiredFields(def.InputSchema)
	requiredKeys := make([]string, 0, len(keys))
	optionalKeys := make([]string, 0, len(keys))
	for _, key := range keys {
		if requiredSet[key] {
			requiredKeys = append(requiredKeys, key)
		} else {
			optionalKeys = append(optionalKeys, key)
		}
	}

	if len(optionalKeys) == 0 {
		_, _ = fmt.Fprintf(b, "class %s(TypedDict):\n", typeName)
		for _, key := range requiredKeys {
			prop := def.InputSchema.Properties[key]
			_, _ = fmt.Fprintf(b, "    %s: %s\n", key, pySchemaType(prop))
		}
		_, _ = fmt.Fprintf(b, "\n")
		return
	}

	if len(requiredKeys) == 0 {
		_, _ = fmt.Fprintf(b, "class %s(TypedDict, total=False):\n", typeName)
		for _, key := range optionalKeys {
			prop := def.InputSchema.Properties[key]
			_, _ = fmt.Fprintf(b, "    %s: %s\n", key, pySchemaType(prop))
		}
		_, _ = fmt.Fprintf(b, "\n")
		return
	}

	baseName := "_" + typeName + "Required"
	_, _ = fmt.Fprintf(b, "class %s(TypedDict):\n", baseName)
	for _, key := range requiredKeys {
		prop := def.InputSchema.Properties[key]
		_, _ = fmt.Fprintf(b, "    %s: %s\n", key, pySchemaType(prop))
	}
	_, _ = fmt.Fprintf(b, "\n")
	_, _ = fmt.Fprintf(b, "class %s(%s, total=False):\n", typeName, baseName)
	for _, key := range optionalKeys {
		prop := def.InputSchema.Properties[key]
		_, _ = fmt.Fprintf(b, "    %s: %s\n", key, pySchemaType(prop))
	}
	_, _ = fmt.Fprintf(b, "\n")
}

func writeGeneratedOutput(content, outputPath, language string, totalActions int) error {
	if strings.TrimSpace(outputPath) == "" {
		_, err := fmt.Fprint(os.Stdout, content)
		return err
	}

	if err := os.WriteFile(outputPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write generated snippet: %w", err)
	}

	return printOutput(map[string]any{
		"generated": true,
		"language":  language,
		"path":      outputPath,
		"actions":   totalActions,
	})
}

func sortedNamespaces(grouped map[string][]actions.ActionDefinition) []string {
	out := make([]string, 0, len(grouped))
	for namespace := range grouped {
		out = append(out, namespace)
	}
	sort.Strings(out)
	return out
}

func countGroupedActions(grouped map[string][]actions.ActionDefinition) int {
	total := 0
	for _, defs := range grouped {
		total += len(defs)
	}
	return total
}

func sortedPropertyKeys(schema *actions.Schema) []string {
	if schema == nil {
		return nil
	}
	out := make([]string, 0, len(schema.Properties))
	for key := range schema.Properties {
		out = append(out, key)
	}
	sort.Strings(out)
	return out
}

func requiredFields(schema *actions.Schema) map[string]bool {
	required := map[string]bool{}
	if schema == nil {
		return required
	}
	for _, key := range schema.Required {
		required[key] = true
	}
	return required
}

func actionInputTypeName(actionName string) string {
	parts := strings.FieldsFunc(actionName, func(r rune) bool {
		return r == '.' || r == '-'
	})
	var b strings.Builder
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed == "" {
			continue
		}
		runes := []rune(strings.ToLower(trimmed))
		runes[0] = unicode.ToUpper(runes[0])
		b.WriteString(string(runes))
	}
	b.WriteString("Input")
	return b.String()
}

func tsSchemaType(schema *actions.Schema) string {
	if schema == nil {
		return "unknown"
	}
	switch strings.ToLower(strings.TrimSpace(schema.Type)) {
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		itemType := tsSchemaType(schema.Items)
		if itemType == "" {
			itemType = "unknown"
		}
		return itemType + "[]"
	case "object":
		return "Record<string, unknown>"
	default:
		return "unknown"
	}
}

func pySchemaType(schema *actions.Schema) string {
	if schema == nil {
		return "Any"
	}
	switch strings.ToLower(strings.TrimSpace(schema.Type)) {
	case "string":
		return "str"
	case "integer":
		return "int"
	case "number":
		return "float"
	case "boolean":
		return "bool"
	case "array":
		itemType := pySchemaType(schema.Items)
		if itemType == "" {
			itemType = "Any"
		}
		return "list[" + itemType + "]"
	case "object":
		return "dict[str, Any]"
	default:
		return "Any"
	}
}

func usageLine(def actions.ActionDefinition) string {
	if def.InputSchema == nil {
		return "kimbap call " + def.Name
	}

	hasComplex := false
	for _, key := range def.InputSchema.Required {
		if prop, ok := def.InputSchema.Properties[key]; ok {
			t := strings.ToLower(strings.TrimSpace(prop.Type))
			if t == "object" || t == "array" {
				hasComplex = true
				break
			}
		}
	}
	if hasComplex {
		return fmt.Sprintf("kimbap call %s --json '{...}'", def.Name)
	}

	parts := []string{"kimbap", "call", def.Name}
	for _, key := range def.InputSchema.Required {
		parts = append(parts, "--"+key, usageValue(def.InputSchema.Properties[key]))
	}
	return strings.Join(parts, " ")
}

func usageValue(schema *actions.Schema) string {
	if schema == nil {
		return "\"value\""
	}
	switch strings.ToLower(strings.TrimSpace(schema.Type)) {
	case "integer", "number":
		return "1"
	case "boolean":
		return "true"
	case "array":
		return "\"[]\""
	case "object":
		return "\"{}\""
	default:
		return "\"value\""
	}
}

var tsReservedWords = map[string]bool{
	"break": true, "case": true, "catch": true, "class": true, "const": true,
	"continue": true, "debugger": true, "default": true, "delete": true, "do": true,
	"else": true, "enum": true, "export": true, "extends": true, "false": true,
	"finally": true, "for": true, "function": true, "if": true, "import": true,
	"in": true, "instanceof": true, "new": true, "null": true, "return": true,
	"super": true, "switch": true, "this": true, "throw": true, "true": true,
	"try": true, "typeof": true, "var": true, "void": true, "while": true, "with": true,
}

func tsFieldName(name string) string {
	if tsReservedWords[name] || !isIdentifier(name) {
		return fmt.Sprintf("%q", name)
	}
	return name
}

var pythonKeywords = map[string]bool{
	"False": true, "None": true, "True": true, "and": true, "as": true,
	"assert": true, "async": true, "await": true, "break": true, "class": true,
	"continue": true, "def": true, "del": true, "elif": true, "else": true,
	"except": true, "finally": true, "for": true, "from": true, "global": true,
	"if": true, "import": true, "in": true, "is": true, "lambda": true,
	"nonlocal": true, "not": true, "or": true, "pass": true, "raise": true,
	"return": true, "try": true, "while": true, "with": true, "yield": true,
}

func isIdentifier(value string) bool {
	if value == "" {
		return false
	}
	for i, r := range value {
		if i == 0 {
			if !unicode.IsLetter(r) && r != '_' {
				return false
			}
			continue
		}
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' {
			return false
		}
	}
	return true
}
